# Generated by Django 5.2.7 on 2025-10-27 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_task_status_attachment_tasklist_task_task_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('NC', 'Not Completed'), ('C', 'Complete')], default='NC', max_length=20),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='status',
            field=models.CharField(choices=[('NC', 'Not Completed'), ('C', 'Complete')], default='NC', max_length=20),
        ),
    ]
