# Generated by Django 5.2.7 on 2025-10-17 18:18

import django.db.models.deletion
import house.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('image', models.ImageField(blank=True, null=True, upload_to=house.models.GenerateHouseImagePath())),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('points', models.IntegerField(default=0)),
                ('completed_task', models.IntegerField(default=0)),
                ('not_completed_task', models.IntegerField(default=0)),
                ('manager', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_house', to='users.profile')),
            ],
        ),
    ]
