# Generated by Django 5.2.7 on 2025-10-22 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={'verbose_name_plural': 'Houses'},
        ),
    ]
